before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - rustc --version
  - rustc src/main.rs
notifications:
  irc:
    - "chat.freenode.net##newboston"
    - "irc.fyrechat.net#vana-commits"
